version: '3.4'

services:
  userservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  blogservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8080"  # Map container port 8080 to host port 8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  commentservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:8080"  # Map container port 8080 to host port 8082
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  imageservices:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:8080"  # Map container port 8080 to host port 8083
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
